#!/bin/bash

# Create virtual environment
python3 -m pip install virtualenv
python3 -m virtualenv .venv
source .venv/bin/activate

# Install dependencies
pip install -r requirements.txt # pip freeze > requirements.txt

# Setup database and create default users
python3 manage.py makemigrations
python3 manage.py migrate # It executes migration files (generated by manage.py makemigrations command) to update the database schema
python3 manage.py shell << EOF
from django.contrib.auth.models import User
from secret_manager.models import Secret

# Create default users
User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
User.objects.create_user('alice', 'alice@example.com', 'AlicePassword123!')
User.objects.create_user('bob', 'bob@example.com', 'BobPassword123!')

# Create some sample secrets
alice = User.objects.get(username='alice')
bob = User.objects.get(username='bob')

Secret.objects.create(
    user=alice,
    title="Bank Account",
    content="Username: alice_bank, Password: s3cr3t123",
)

Secret.objects.create(
    user=alice,
    title="Treasure Location",
    content="Under the oak tree in the backyard",
)

Secret.objects.create(
    user=bob,
    title="Email Password",
    content="Email: bob_sub@example.com, Password: b0b3m@il",
)
EOF

echo "Setup complete. Use 'bash ./run.sh' to start the server."