# Generated by Django 5.2.3 on 2025-06-18 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
