# Generated by Django 5.2.3 on 2025-06-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0002_secret_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='content',
            new_name='secret_key',
        ),
        migrations.AddField(
            model_name='secret',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secret',
            name='secret_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
